Comment

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,81 +1,81 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir>
 
-# Debug, echo every command
-if [[ -n "$BUILDPACK_DEBUG" ]]; then
-  set -x
-fi
+# # Debug, echo every command
+# if [[ -n "$BUILDPACK_DEBUG" ]]; then
+#   set -x
+# fi
 
-# Fail immediately on non-zero exit code.
-set -e
-# Fail immediately on non-zero exit code within a pipeline.
-set -o pipefail
-# Fail on undeclared variables.
-set -u
+# # Fail immediately on non-zero exit code.
+# set -e
+# # Fail immediately on non-zero exit code within a pipeline.
+# set -o pipefail
+# # Fail on undeclared variables.
+# set -u
 
-echo "=====> Start Calendso"
+# echo "=====> Start Calendso"
 
-BUILD_DIR=$1
-CACHE_DIR=$2
-ENV_DIR=$3
-basedir="$( cd -P "$( dirname "$0" )" && pwd )"
-BP_DIR=`cd $(dirname $0); cd ..; pwd`
+# BUILD_DIR=$1
+# CACHE_DIR=$2
+# ENV_DIR=$3
+# basedir="$( cd -P "$( dirname "$0" )" && pwd )"
+# BP_DIR=`cd $(dirname $0); cd ..; pwd`
 
 
-echo "## start here $basedir $BP_DIR $BUILD_DIR"
-cp $BP_DIR/.buildpacks $BUILD_DIR/.buildpacks
+# echo "## start here $basedir $BP_DIR $BUILD_DIR"
+# cp $BP_DIR/.buildpacks $BUILD_DIR/.buildpacks
 
-# Use architecture of multi-buildpack to compose behavior.
-# https://github.com/Scalingo/multi-buildpack
+# # Use architecture of multi-buildpack to compose behavior.
+# # https://github.com/Scalingo/multi-buildpack
 
-url=https://github.com/Scalingo/multi-buildpack
-branch=""
-dir=$(mktemp -t buildpackXXXXX)
-rm -rf $dir
+# url=https://github.com/Scalingo/multi-buildpack
+# branch=""
+# dir=$(mktemp -t buildpackXXXXX)
+# rm -rf $dir
 
-echo "=====> Downloading Buildpack: $url"
+# echo "=====> Downloading Buildpack: $url"
 
-if [[ "$url" =~ \.tgz$ ]] || [[ "$url" =~ \.tgz\? ]]; then
-  mkdir -p "$dir"
-  curl -s "$url" | tar xvz -C "$dir" >/dev/null 2>&1
-else
-  git clone $url $dir >/dev/null 2>&1
-fi
-cd $dir
+# if [[ "$url" =~ \.tgz$ ]] || [[ "$url" =~ \.tgz\? ]]; then
+#   mkdir -p "$dir"
+#   curl -s "$url" | tar xvz -C "$dir" >/dev/null 2>&1
+# else
+#   git clone $url $dir >/dev/null 2>&1
+# fi
+# cd $dir
 
-if [ "$branch" != "" ]; then
-  git checkout $branch >/dev/null 2>&1
-fi
+# if [ "$branch" != "" ]; then
+#   git checkout $branch >/dev/null 2>&1
+# fi
 
-chmod -f +x $dir/bin/{detect,compile,release}
+# chmod -f +x $dir/bin/{detect,compile,release}
 
-framework=$($dir/bin/detect $1)
+# framework=$($dir/bin/detect $1)
 
-if [ $? == 0 ]; then
-  echo "=====> Detected Framework: $framework"
-  $dir/bin/compile $BUILD_DIR $CACHE_DIR $ENV_DIR
+# if [ $? == 0 ]; then
+#   echo "=====> Detected Framework: $framework"
+#   $dir/bin/compile $BUILD_DIR $CACHE_DIR $ENV_DIR
 
-  if [ $? != 0 ]; then
-    exit 1
-  fi
-else
-  echo "calendso-buildpack `.buildpacks` not defined. Exiting."
-  exit 1
-fi
+#   if [ $? != 0 ]; then
+#     exit 1
+#   fi
+# else
+#   echo "calendso-buildpack `.buildpacks` not defined. Exiting."
+#   exit 1
+# fi
 
-# install addons
-cd $BUILD_DIR
-$BP_DIR/bin/install_calendso.sh
+# # install addons
+# cd $BUILD_DIR
+# $BP_DIR/bin/install_calendso.sh
 
-# prepare conf
-echo "  Prepare conf"
-mkdir -p "$BUILD_DIR/bin"
-cp "$BP_DIR/scripts/run.sh" "$BUILD_DIR/bin/"
+# # prepare conf
+# echo "  Prepare conf"
+# mkdir -p "$BUILD_DIR/bin"
+# cp "$BP_DIR/scripts/run.sh" "$BUILD_DIR/bin/"
 
-[ -f "$BUILD_DIR/config.py" ] || cp "$BP_DIR/config.py" "$BUILD_DIR/config.py"
+# [ -f "$BUILD_DIR/config.py" ] || cp "$BP_DIR/config.py" "$BUILD_DIR/config.py"
 
-for d in errbackends errstorage plugins; do
-  [ -d "$d" ] || mkdir $BUILD_DIR/$d
-done
+# for d in errbackends errstorage plugins; do
+#   [ -d "$d" ] || mkdir $BUILD_DIR/$d
+# done
 
 echo "   scalingo-calendso-buildpack"
